config/routes.rb
Triple8::Application.routes.draw do
  
  scope '(:locale)' do    

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
    
    devise_for :users, :controllers => { 
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :classifieds do
      get :change_sub_categories, on: :collection
      get :delete_selected, on: :collection
      get :owned, on: :collection 
    end     
    
    resources :countries

    resources :categories

    resources :currencies

    resources :users, except: [:new, :create]

    get 'authentications/edit' => 'authentications#edit', as: 'edit_auth'
    put 'authentications/update' => 'authentications#update', as: 'update_auth'
    
    root to: 'home#index', as: 'home'
  end  

  mount TranslationCenter::Engine => "/translation_center"

end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :classifieds

	belongs_to :country

	validates :name, :ratio, :country, presence: true
	validates :name, :uniqueness => {scope: :country_id}
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.haml
= form_for @currency, :html => { :class => 'form-horizontal' } do |f|
  = f.error_messages
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :ratio, :class => 'control-label'
    .controls
      = f.text_field :ratio, :class => 'text_field'
  .control-group
    = f.label :country_id, :class => 'control-label'
    .controls
      = select_field(f, @currency, :country_id, countries,   |
        'id', 'name','choose country', 'select')
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), currencies_path, :class => 'btn'

app/views/currencies/edit.html.haml
- model_class = Currency
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/currencies/index.html.haml
- model_class = Currency
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:ratio)
      %th= model_class.human_attribute_name(:country_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @currencies.each do |currency|
      %tr
        %td= link_to currency.id, currency_path(currency)
        %td= currency.name
        %td= currency.ratio
        %td= currency.country_id
        %td=l currency.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_currency_path(currency), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), currency_path(currency), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_currency_path, :class => 'btn btn-primary'

app/views/currencies/new.html.haml
- model_class = Currency
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/currencies/show.html.haml
- model_class = Currency
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @currency.name
%p
  %strong= model_class.human_attribute_name(:ratio) + ':'
  %br
  = @currency.ratio
%p
  %strong= model_class.human_attribute_name(:country_id) + ':'
  %br
  = @currency.country_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), currencies_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_currency_path(@currency), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), currency_path(@currency), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'