config/routes.rb
Triple8::Application.routes.draw do
  
  scope '(:locale)' do    

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
    
    devise_for :users, :controllers => { 
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :classifieds do
      get :change_sub_categories, on: :collection
      get :delete_selected, on: :collection
      get :owned, on: :collection 
    end     
    
    resources :countries

    resources :categories

    resources :currencies

    resources :users, except: [:new, :create]

    get 'authentications/edit' => 'authentications#edit', as: 'edit_auth'
    put 'authentications/update' => 'authentications#update', as: 'update_auth'
    
    root to: 'home#index', as: 'home'
  end  

  mount TranslationCenter::Engine => "/translation_center"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!
  	
  def index
    if params[:set_locale]
      redirect_to home_path(locale: params[:set_locale])
    else
      @search = Classified.search(params[:search])
      @classifieds = @search.paginate(per_page: 10, page: params[:page],
            order: "#{sort_column(Classified)} #{sort_direction}")

      respond_to do |format|
        format.html # index.html.haml
        format.json { render json: @classifieds }
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- model_class = Classified
%fieldset
  %legend= t'const.search'
  = form_for @search, :url => home_path, :html => {method: :get,            |
    :class => 'form-horizontal'} do |s|
    = s.text_field :title_contains, placeholder: (t 'const.title')
    %br    
    = s.radio_button :kind_eq, Classified::KINDS[0], checked: true
    = s.label :wanted, t("const.#{Classified::KINDS[0].downcase}"), :class => 'inline-label'
    = s.radio_button :kind_eq, Classified::KINDS[1]
    = s.label :for_sale, t("const.#{Classified::KINDS[1].downcase}"), :class => 'inline-label'
    %br
    = s.text_field :country_name_contains, placeholder: (t 'const.location')
    %br    
    %strong= t('const.refine_search')
    %br
    = select_field(s, @search, :main_category_id_eq, main_categories,   |
      'id', 'name',t('const.main_category'), 'select', true)
    = render('classifieds/sub_category_select', sub_categories: sub_categories(@search.main_category_id_eq), name: 'search[sub_category_id_eq]', selected_category: @search.sub_category_id_eq, element_id: 'search_sub_category_id_eq')
    %br
    = s.text_field :price_gte, placeholder: (t 'const.min_price')
    = s.text_field :price_lte, placeholder: (t 'const.max_price')
    %br
    = s.text_field :created_at_or_updated_at_gte,                   |
      value: @search.created_at_or_updated_at_gte.try(:to_date), |
      :class => 'date', placeholder: (t 'const.posted_on_or_after')
    %br   
    = s.submit

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:image)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:category)
      %th= model_class.human_attribute_name(:kind)
      %th= sortable(Classified, 'price', model_class.human_attribute_name(:price))
      %th= sortable(Classified, 'created_at', model_class.human_attribute_name(:created_at))
      %th= model_class.human_attribute_name(:Share)
  %tbody
    - @classifieds.each do |classified|
      %tr
        %td= link_to image_tag(classified.attachments.first.try(:file).try(:url,:thumb)), classified_path(classified)
        %td= classified.title
        %td
          = classified.main_category.name
          %br
          = classified.sub_category.name
        %td= t("const.#{classified.kind.downcase}")
        %td= format_price classified
        %td= l classified.created_at.to_date
        %td
          = link_to image_tag(''), "http://facebook.com/sharer.php?u=#{classified_url classified}", target: '_blank'
          = link_to image_tag(''), "https://twitter.com/share?url=#{classified_url classified}&text=#{classified.title}", target: '_blank'
          = link_to image_tag(''), "http://linkedin.com/shareArticle?url=#{classified_url classified}", target: '_blank'

= will_paginate(@classifieds)
        