config/routes.rb
Triple8::Application.routes.draw do
  
  scope '(:locale)' do    

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
    
    devise_for :users, :controllers => { 
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :classifieds do
      get :change_sub_categories, on: :collection
      get :delete_selected, on: :collection
      get :owned, on: :collection 
    end     
    
    resources :countries

    resources :categories

    resources :currencies

    resources :users, except: [:new, :create]

    get 'authentications/edit' => 'authentications#edit', as: 'edit_auth'
    put 'authentications/update' => 'authentications#update', as: 'update_auth'
    
    root to: 'home#index', as: 'home'
  end  

  mount TranslationCenter::Engine => "/translation_center"

end

app/models/classified.rb
class Classified < ActiveRecord::Base
	
	KINDS = [ 'Wanted', 'For Sale']
	MAX_ATTACHMENTS_NO = 3

	has_many :attachments, dependent: :destroy
	

	belongs_to :main_category, class_name: 'Category'
	belongs_to :sub_category, class_name: 'Category'
	belongs_to :country
	belongs_to :currency
	belongs_to :user

	accepts_nested_attributes_for :attachments, allow_destroy: true

	attr_protected :user_id
	
	before_save :set_identifier

	validates :title, :kind, :user_id, :longitude, :latitude, :country_id,
	  :main_category_id, :sub_category_id, :price, :currency_id, presence: true

	validates :kind, inclusion: KINDS
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validate :categories_validations
	validate :attachments_validations

	def to_param
		identifier
	end

	def set_identifier
		self.identifier = self.title.parameterize +
		 "#{self.id}#{Random.new.rand(100..999)}"
	end

	def attachments_validations
		if self.attachments.count > MAX_ATTACHMENTS_NO
			self.errors.add(:base, I18n.t(
				"models.classified.errors.max_attachments_no_exceeds"))
		end
	end

	def categories_validations
		if self.main_category and self.main_category.main_category?
			unless self.main_category.include_sub_category? self.sub_category
				errors.add(:base, I18n.t(
						"models.classified.errors.invalid_sub_category"))
			end
		else
			errors.add(:base, I18n.t(
				"models.classified.errors.invalid_main_category"))
		end
	end

	def complete_attachments_number
      i = MAX_ATTACHMENTS_NO - self.attachments.count
      i.times {self.attachments.build}
    end

end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:show,
   :change_sub_categories]
  before_filter :index_for_admin_or_normal, only: [:index]

  # GET /classifieds
  # GET /classifieds.json
  def index
    @search = Classified.search(params[:search])
    @classifieds = @search.paginate( per_page: 10, page: params[:page],
          order: "#{sort_column(Classified)} #{sort_direction}")
    
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @classifieds }
    end
  end

  def owned
    @search = current_user.classifieds.search(params[:search])
    @classifieds = @search.paginate per_page: 10, page: params[:page],
          order: "#{sort_column(Classified)} #{sort_direction}"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classifieds }
    end
  end

  # GET /classifieds/1
  # GET /classifieds/1.json
  def show
    @classified = Classified.find_by_identifier(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classified }
    end  
  end

  # GET /classifieds/new
  # GET /classifieds/new.json
  def new
    @classified = Classified.new
    @classified.phone = current_user.phone
    @classified.email = current_user.email
    @classified.country = current_user.country
    @classified.latitude = request.location.latitude
    @classified.longitude = request.location.longitude
    3.times {@classified.attachments.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classified }
    end
  end

  # GET /classifieds/1/edit
  def edit
    @classified = Classified.find_by_identifier(params[:id])

    if must_be_owned?
      @classified.complete_attachments_number
      main_category = Category.find_by_id(@classified.main_category_id)
      @sub_categories = main_category.nil? ? [] : main_category.children    
    end 
  end

  # POST /classifieds
  # POST /classifieds.json
  def create
    @classified = Classified.new(params[:classified])
    @classified.user_id = current_user.id

    respond_to do |format|
      if @classified.save        
        
        current_user.facebook_share(classified_url(@classified),
         @classified.title) if(params[:facebook_share])
      
        current_user.twitter_share(classified_url(@classified),
         @classified.title) if(params[:twitter_share])
      
        current_user.linkedin_share(classified_url(@classified),
         @classified.title) if(params[:linkedin_share])

        format.html { 
          redirect_to @classified,
            notice: I18n.t('application.messages.successfully_created',
              model: 'classified') 
        }
        format.json { 
          render json: @classified, status: :created,
            location: @classified 
        }
      else
        @classified.complete_attachments_number
        main_category = Category.find_by_id(params[:classified][:main_category_id])
        @sub_categories = main_category.nil? ? [] : main_category.children
        format.html { render action: "new" }
        format.json { render json: @classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /classifieds/1
  # PUT /classifieds/1.json
  def update
    @classified = Classified.find_by_identifier(params[:id])
    if must_be_owned?
      respond_to do |format|
        if @classified.update_attributes(params[:classified])
          format.html { 
            redirect_to @classified,
              notice: I18n.t('application.messages.successfully_updated',
               model: 'classified') 
          }
          format.json { head :ok }
        else
          @classified.complete_attachments_number
          main_category = Category.find_by_id(@classified.main_category_id)
          @sub_categories = main_category.nil? ? [] : main_category.children
          format.html { render action: "edit" }
          format.json { 
            render json: @classified.errors,
             status: :unprocessable_entity 
          }
        end
      end  
    end    
  end

  # DELETE /classifieds/1
  # DELETE /classifieds/1.json
  def destroy
    @classified = Classified.find_by_identifier(params[:id])
    if must_be_owned?
      @classified.destroy

      respond_to do |format|
        format.html { redirect_to classifieds_url }
        format.json { head :ok }
      end
    end
  end

  def change_sub_categories
    main_category = Category.find_by_id(params[:main_category])
    @sub_categories = main_category.nil? ? [] : main_category.children
    @sub_categories_id = params[:sub_categories_id]
    @name = params[:name]
  end

  def delete_selected
    ids = params[:ids].split(',')
    classifieds = Classified.find_all_by_identifier ids
    classifieds.each do |classified|
      classified.destroy
    end
    redirect_to classifieds_url(locale: params[:locale])
  end

  private

  def must_be_owned?
    return true if current_user.admin?
    if @classified.user != current_user
      redirect_to_back I18n.t("application.messages.insufficient_privilage")
      return false
    end
    return true
  end

  def index_for_admin_or_normal
    redirect_to(owned_classifieds_path) unless current_user.type == 'Admin'    
  end
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper

end

app/views/classifieds/_form.html.haml
- @sub_categories ||= []  

- content_for :pre_head do
  <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDpqZNzU0SeaUhvgT6IA0uw0YJ2RqxkVDM&sensor=false">
  </script>

%div#googleMap
:javascript
  $(function(){
    initializeMap(#{@classified.latitude}, #{@classified.longitude});
  });  

= form_for @classified, :html => { :class => 'form-horizontal test', multipart: true } do |f|
      
  = f.error_messages

  = f.hidden_field :latitude
  = f.hidden_field :longitude

  .control-group
    = f.label :kind, :class => 'control-label'
    .controls
      = f.radio_button :kind, Classified::KINDS[0], checked: true
      = f.label :wanted, t("const.#{Classified::KINDS[0].downcase}"), :class => 'inline-label'
      = f.radio_button :kind, Classified::KINDS[1]
      = f.label :for_sale, t("const.#{Classified::KINDS[1].downcase}"), :class => 'inline-label'
  .control-group
    = f.label :main_category_id, :class => 'control-label'
    .controls
      = select_field(f, @classified, :main_category_id, main_categories, "id",    |
        "name", t('const.main_category'), 'select')
  .control-group
    = f.label :sub_category_id, :class => 'control-label'
    .controls
      = render('sub_category_select', sub_categories: @sub_categories, |
        selected_category: @classified.sub_category_id,                |
        name: 'classified[sub_category_id]', element_id: 'classified_sub_category_id')
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .control-group
    = f.label :price, :class => 'control-label'
    .controls
      = f.number_field :price, :class => 'number_field', step: 0.01
      = select_field(f, @classified, :currency_id, currencies, "id",    |
        "name", 'currency', 'select')
  .control-group
    = f.label :phone, :class => 'control-label'
    .controls
      = f.text_field :phone, :class => 'text_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label :country_id, :class => 'control-label'
    .controls
      = select_field(f, @classified, :country_id, locations, "id",    |
        "name", 'Select country', 'select')
  .control-group
    = f.label :tags, :class => 'control-label'
    .controls
      = f.text_field :tags, :class => 'text_field'
  = f.fields_for :attachments do |b|
    .control-group
      = b.label :photo, :class => 'control-label'
      .controls
        = b.file_field :file, :class => 'file_field'
  - unless @classified.persisted?
    %label
      =check_box_tag 'facebook_share', "1", false,                |
        disabled: current_user.can_share_on?(:facebook)? false : true
      %i share on facebook

    %label
      =check_box_tag 'twitter_share', "1", false,                |
        disabled: current_user.can_share_on?(:twitter)? false : true
      %i share on twitter

    %label
      =check_box_tag 'linkedin_share', "1", false,                |
        disabled: current_user.can_share_on?(:linkedin)? false : true
      %i share on linkedin

    %label connect to more networks to spread the word

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      classifieds_path, :class => 'btn'                            |

app/views/classifieds/_list_classifieds.html.haml
%div#classifieds_listing
  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:edit)      
        %th= model_class.human_attribute_name(:id)
        %th= model_class.human_attribute_name(:kind)
        %th= model_class.human_attribute_name(:title)
        %th= model_class.human_attribute_name(:main_category)
        %th= model_class.human_attribute_name(:sub_category)
        %th= model_class.human_attribute_name(:description)
        %th= sortable(Classified, 'price', model_class.human_attribute_name(:price))
        %th= model_class.human_attribute_name(:creator)
        %th= sortable(Classified, 'created_at', model_class.human_attribute_name(:created_at))
        %th= model_class.human_attribute_name(:delete)
        %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @classifieds.each do |classified|
        %tr
          %td= radio_button_tag 'edit', false, false, :'data-url'=> edit_classified_path(classified)
          %td= link_to classified.id, classified_path(classified)
          %td= t "const.#{classified.kind.downcase}"
          %td= classified.title
          %td= classified.main_category.name
          %td= classified.sub_category.name
          %td= classified.description
          %td= format_price classified
          %td= classified.user.name
          %td= l classified.created_at
          %td= check_box_tag 'delete', false, false, :'data-id'=> classified.identifier
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")),   |
              edit_classified_path(classified), :class => 'btn btn-mini' 

            = link_to t('.destroy', :default => t("helpers.links.destroy")),   |
              classified_path(classified), :method => :delete,                 |
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm",  |
              :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

  = link_to t('.new', :default => t("helpers.links.new")), |
    new_classified_path, :class => 'btn btn-primary'
  = link_to t('const.edit_selected'), url_for, class: 'btn btn-primary', id: :edit_selected
  = link_to t('const.delete_selected'), url_for, class: 'btn btn-primary', id: :delete_selected,    |
    data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }

app/views/classifieds/_sub_category_select.html.haml
- selected_category ||= params[:classified] ? params[:classified][:sub_category_id] : 0

= select_tag '',                                                                       |
  options_from_collection_for_select(sub_categories,"id","name", selected_category),   |
  prompt: 'sub category', :class => 'select', id: element_id, |
  name: name

app/views/classifieds/change_sub_categories.js.haml
$("##{@sub_categories_id}").html("#{j render 'sub_category_select', sub_categories: @sub_categories, name: @name, element_id: @sub_categories_id}");

app/views/classifieds/delete_selected.js.haml
# - model_class = Classified
# $("#classifieds_listing").html("#{j render('list_classifieds', model_class: model_class)}");

app/views/classifieds/edit.html.haml
- model_class = Classified
.page-header
  %h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, |
      :default => "Edit #{model_class.model_name.human}")                                      |
= render :partial => 'form'

app/views/classifieds/index.html.haml
- model_class = Classified
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize

= form_for @search, :url => classifieds_path, :html => {method: :get,            |
  :class => 'form-horizontal'} do |s|
  = s.radio_button :kind_eq, Classified::KINDS[0], checked: true
  = s.label :wanted, t("const.#{Classified::KINDS[0].downcase}"), class: 'inline-label'
  = s.radio_button :kind_eq, Classified::KINDS[1]
  = s.label :for_sale, t("const.#{Classified::KINDS[1].downcase}"), class: 'inline-label'  
  %br
  = s.text_field :user_name_contains, placeholder: (t 'const.name')
  %br  
  %table
    %tr
      %td  
        = s.text_field :title_contains, placeholder: (t 'const.title')
      %td
        = s.text_field :description_contains, placeholder: (t 'const.description') 
    %tr    
      %td  
        = select_field(s, @search, :main_category_id_eq, main_categories,   |
          'id', 'name',t('const.main_category'), 'select', true)
      %td
        = render('classifieds/sub_category_select', sub_categories: sub_categories(@search.main_category_id_eq), name: 'search[sub_category_id_eq]', selected_category: @search.sub_category_id_eq, element_id: 'search_sub_category_id_eq')
    %tr
      %td
        = s.text_field :country_name_like, placeholder: (t 'const.location')
  %br
  = s.text_field :price_gte, placeholder: (t 'const.min_price')
  = s.text_field :price_lte, placeholder: (t 'const.max_price')
  %br
  = s.text_field :created_at_gte, placeholder: (t 'const.posted_after'), :class => 'date'
  = s.text_field :updated_at_lte, placeholder: (t 'const.posted_before'),:class => 'date'
  %br  
  = s.text_field :tags_contains, placeholder: (t 'const.tags')
  %br
  = s.submit

= render('list_classifieds', model_class: model_class)

= will_paginate(@classifieds)

app/views/classifieds/new.html.haml
- model_class = Classified
.page-header
  %h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => 'form'

app/views/classifieds/owned.html.haml
- model_class = Classified
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize

%fieldset
  %legend= t'.Search'
  = form_for @search, :url => owned_classifieds_path, :html => {method: :get,            |
    :class => 'form-horizontal'} do |s|
    = s.text_field :title_contains, placeholder: (t 'const.title')
    %br    
    = s.radio_button :kind_eq, Classified::KINDS[0], checked: true
    = s.label :wanted, t("const.#{Classified::KINDS[0].downcase}"), class: 'inline-label'
    = s.radio_button :kind_eq, Classified::KINDS[1]
    = s.label :for_sale, t("const.#{Classified::KINDS[1].downcase}"), class: 'inline-label'
    %br
    = s.text_field :country_name_contains, placeholder: (t 'const.location')
    %br    
    %strong= t 'const.refine_search'
    %br
    = select_field(s, @search, :main_category_id_eq, main_categories,   |
      'id', 'name',t('const.main_category'), 'select', true)
    = render('classifieds/sub_category_select', sub_categories: sub_categories(@search.main_category_id_eq), name: 'search[sub_category_id_eq]', selected_category: @search.sub_category_id_eq, element_id: 'search_sub_category_id_eq')
    %br
    = s.text_field :price_gte, placeholder: (t 'const.min_price')
    = s.text_field :price_lte, placeholder: (t 'const.max_price')
    %br
    = s.text_field :created_at_or_updated_at_gte, :class => 'date',             |
      placeholder: (t 'const.posted_on_or_after')
    %br   
    = s.submit

= render('list_classifieds', model_class: model_class)
= will_paginate(@classifieds)

app/views/classifieds/show.html.haml
- model_class = Classified
- @head_attributes = { prefix:"og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# eight_eight_eight: http://ogp.me/ns/fb/eight_eight_eight#" }
- content_for :pre_head do
  %meta{property: "og:title", content: @classified.title}
  %meta{property: "og:description", content: @classified.description}   
  %meta{property: "og:type", content: "#{Triple8::Application.config.fb_namespace}:classified"}
  %meta{property: "og:image", content: "#{request.protocol}#{request.host_with_port}#{@classified.attachments.first.try(:file).try(:url, :medium)}"}
  
.page-header
  %h1= t '.title', :default => model_class.model_name.human
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:kind)
      \:
  %dd= t("const.#{@classified.kind.downcase}")
  %dt
    %strong
      = model_class.human_attribute_name(:main_category_id)
      \:
  %dd= @classified.main_category.name
  %dt
    %strong
      = model_class.human_attribute_name(:sub_category_id)
      \:
  %dd= @classified.sub_category.name
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= @classified.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= @classified.description
  %dt
    %strong
      = model_class.human_attribute_name(:price)
      \:
  %dd= format_price @classified
  %dt
    %strong
      = model_class.human_attribute_name(:country)
      \:
  %dd= @classified.country.try :name
  %dt
    %strong
      = model_class.human_attribute_name(:tags)
      \:
  %dd= @classified.tags
  - @classified.attachments.each do |photo|
    %dt= link_to 'See attachment', photo.file.url(:medium), target: "_blank"
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    classifieds_path, :class => 'btn'                        |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_classified_path(@classified), :class => 'btn'       |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    classified_path(@classified),                                                                                |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |