config/routes.rb
Triple8::Application.routes.draw do
  
  scope '(:locale)' do    

    devise_scope :user do
      get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    end
    
    devise_for :users, :controllers => { 
      omniauth_callbacks: "users/omniauth_callbacks"
    }

    resources :classifieds do
      get :change_sub_categories, on: :collection
      get :delete_selected, on: :collection
      get :owned, on: :collection 
    end     
    
    resources :countries

    resources :categories

    resources :currencies

    resources :users, except: [:new, :create]

    get 'authentications/edit' => 'authentications#edit', as: 'edit_auth'
    put 'authentications/update' => 'authentications#update', as: 'update_auth'
    
    root to: 'home#index', as: 'home'
  end  

  mount TranslationCenter::Engine => "/translation_center"

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head{ @head_attributes|| {} }
    = yield :pre_head
    = javascript_include_tag "application"
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "08-08-08"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For third-generation iPad with high-resolution Retina display:
    / Size should be 144 x 144 pixels
    = favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    / For iPhone with high-resolution Retina display:
    / Size should be 114 x 114 pixels
    = favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    / For first- and second-generation iPad:
    / Size should be 72 x 72 pixels
    = favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    / Size should be 57 x 57 pixels
    = favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon'
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Triple8
          .container.nav-collapse
            %ul.nav
              %li= link_to t("const.home"), home_path
              - if current_user
                - if current_user.admin?
                  %li= link_to t("const.categories"), categories_path
                  %li= link_to t("const.classifieds"), classifieds_path
                  %li= link_to t("const.countries"), countries_path
                  %li= link_to t("const.currencies"), currencies_path
                  %li= link_to t("const.users"), users_path
                %li= link_to t("const.my_classifieds"), owned_classifieds_path                
              - if notice
                %li= link_to notice
            %ul.locale
              - other_language = alterative_language
              %li= link_to other_language[0], url_for(locale: other_language[1])
              
              
          / /.nav-collapse
    .container
      .row
        .span10
          = yield
        .span2
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header= current_user.nil? ? "guest" : current_user.name
              - if current_user
                %li= link_to t("const.edit_account"), edit_user_registration_path
                %li= link_to t("const.sign_out"), destroy_user_session_path,     |
                      method: :delete
              - else  
                %li= link_to t("const.sign_up"), new_user_registration_path
                %li= link_to t("const.sign_in"), new_user_session_path            
          / /.well
        / /span
      / /row
      %footer
        %p &copy; BadrIT 2013
    / /container
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    